Delete case
PUM-05/backend pull request #29
Opened 2023-04-01 13:37 UTC by Jack-Kolm

2023-04-01 13:58 UTC, f-i-l-i-p requested changes

2023-04-01 13:58 UTC, f-i-l-i-p commented on src/api/tests.py
> +        """
```suggestion
        """
        Tests that the check endpoint returns a 204 status code when a case is found
        and deleted, as well as if the number of cases have changed and if querying a
        deleted object will result in an error.
        """
```

2023-04-02 12:30 UTC, f-i-l-i-p approved these changes

2023-04-02 13:11 UTC, GoaGifflar approved these changes

2023-04-02 13:11 UTC, merged