GET with parameters implemented, tested and README updated
PUM-05/backend pull request #41
Opened 2023-04-12 20:32 UTC by GoaGifflar

2023-04-13 06:24 UTC, anton-bergman submitted a review, later dismissed

2023-04-13 09:59 UTC, f-i-l-i-p submitted a review, later dismissed

2023-04-13 09:59 UTC, f-i-l-i-p commented on src/api/interfaces/cases.py
> +
Tom rad?

```suggestion
```

2023-04-13 09:59 UTC, f-i-l-i-p commented on src/api/interfaces/cases.py
Jag tror inte att vi behöver `index-start` och `index-end` längre eftersom vi istället har `per-page` och `page` för att bestämma hur många ärenden som ska retruneras i samma request.

2023-04-13 11:10 UTC, GoaGifflar commented on src/api/models.py
> +        ordering = ['-id']
Sant, bytte till id då sorteringen blev godtycklig när objekten skapades samtidigt i testerna vilket gjorde att deras ordning blev slumpad. Sätter id som sekundär med created_at som primär

2023-04-13 11:10 UTC, GoaGifflar commented on src/api/interfaces/cases.py
Tar bort det + lite andra ändringar

2023-04-13 11:55 UTC, f-i-l-i-p requested changes

2023-04-13 11:55 UTC, f-i-l-i-p commented on src/api/models.py
> +    user = models.ManyToManyField(User)
Blivit något merge-fel här? Tror vi bytte ut `user` till `created_by` och `edited_by`

2023-04-13 11:55 UTC, f-i-l-i-p commented on README.md
> +GET /api/case/category-id=2&medium=phone&per-page=20&page=3
Visste inte riktigt vart jag ska lägga den här kommentaren men det verkar som att den här lösningen inte använder http query strings utan någon typ av hybridlösning med paths?

Django letar efter ett frågetecken och formaterar allt efter det som query parametrar. Så en exempel request borde vara:
``` http
GET /api/case?category-id=2&medium=phone&per-page=20&page=3
```
Då kan man få fram parametrarna med t.ex.:
``` python
request.GET.get("per-page", default="100")
```
Och man borde då inte behöva ha `str_params` i `case` i _views.py_ eller i _urls.py_.

2023-04-13 12:18 UTC, GoaGifflar commented on README.md
> +GET /api/case/category-id=2&medium=phone&per-page=20&page=3
Fixar, hade missuppfattat

2023-04-13 12:27 UTC, f-i-l-i-p commented on src/api/interfaces/cases.py
> +    page = int(parameters.get("page", 1))
Nej, missade att det fångas i viewn.

2023-04-13 12:27 UTC, f-i-l-i-p approved these changes

2023-04-13 12:34 UTC, GoaGifflar commented on src/api/interfaces/cases.py
> +    query = Q(**{params[k]: v for k, v in parameters.items() if k in params.keys()})    # magic
Ska ske, är lite hokus pokus men förstod tillräckligt för att modifiera den.

2023-04-17 07:32 UTC, Jack-Kolm approved these changes

2023-04-17 07:32 UTC, merged