add category name in cases, cannot be manually set
PUM-05/backend pull request #48
Opened 2023-04-24 09:38 UTC by GoaGifflar

2023-04-24 09:54 UTC, f-i-l-i-p requested changes

2023-04-24 10:02 UTC, GoaGifflar commented on src/api/models.py
Sant tänkte inte på det så det blir nog enklare så, fixar det snart

2023-04-24 11:41 UTC, f-i-l-i-p commented on src/api/interfaces/cases.py
>          has_more = False
Ser ut som att `cases` inte används?

2023-04-24 11:54 UTC, GoaGifflar commented on src/api/interfaces/cases.py
>          has_more = False
fixat

2023-04-24 11:55 UTC, f-i-l-i-p approved these changes

2023-04-25 12:59 UTC, Jack-Kolm approved these changes
Approved

2023-04-25 13:00 UTC, merged